name: app_front_dark_solution
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  lottie: ^1.4.3
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/LogoAndroid_250p.png'
  adaptive_icon_background: 'assets/icon/LogoAndroid_250p.png'


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/